apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - service.yaml
  - configmap.yaml
  - deployment.yaml

images:
  - name: registry.fullstack.pw/library/cks-backend
    newTag: pr-will-be-replaced

configMapGenerator:
  - name: cks-backend-config
    behavior: merge
    envs:
      - configmap

replicas:
  - name: cks-backend
    count: 1
